Ginkgo update and test fixes
linode/linode-k8s-e2e-tests pull request #8
Opened 2023-02-01 15:58 UTC by mrogers950

This updates the ginkgo/gomega versions, and adds other fixes for NetworkPolicy test. Notably, the google-samples/hello-frontend image was too old to apt-get update and install curl (the debian base was EOL). This replaces the image with an updated one built from this repo.

Additionally, a side effect of updating nginx was a failure to start due to the frontend service name, expected to be "hello": 
`(nginx: [emerg] host not found in upstream "hello" in /etc/nginx/conf.d/frontend.conf:2)`. 
To fix this the service names are adjusted.

TODO:
- Replace personal repo with linode repo after pushing
- Confirm stateful WP test passes

2023-02-06 16:18 UTC, git-it127 requested changes
Looks Good. Small suggestion here.

2023-02-06 16:18 UTC, git-it127 commented on images/hello-frontend/Dockerfile
> +FROM debian:latest
Can we please pin this to a specific version instead of `latest`? So it is known what version and to have consistency.

2023-02-07 21:27 UTC, mrogers950 commented on images/hello-frontend/Dockerfile
> +FROM debian:latest
Good idea, I'll correct it.

2023-02-08 18:27 UTC, git-it127 approved these changes

2023-02-08 19:40 UTC, scmeggitt approved these changes
Looks good to me

2023-02-09 14:18 UTC, merged